language: node_js
node_js:
  - "stable"
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_deploy:
  - npm run build # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
